###################CREAR PACIENTE POR ID
POST http://localhost:8081/turnos/registrar HTTP/1.1
Content-Type: application/json

{
"paciente":1,
"odontologo":1,
"fechaYHora": "2023-11-15T17:15:00"
}

###################BUSCAR TURNO POR ID
GET http://localhost:8081/turnos/3 HTTP/1.1

###################BUSCAR TODOS LOS TURNOS
GET http://localhost:8081/turnos/listar HTTP/1.1

###################ACTUALIZAR TURNOS POR ID
PUT http://localhost:8081/turnos/actualizar HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "paciente": {
    "id": 1,
    "nombre": "Carlos",
    "apellido": "Mora",
    "dni": 123456,
    "fechaIngreso": "2023-12-10",
    "domicilio": {
      "id": 1,
      "calle": "argomedo",
      "numero": 344,
      "localidad": "santiago",
      "provincia": "santiago"
    }
  },
  "odontologo": {
    "id": 1,
    "matricula": "123456789111",
    "nombre": "Astrid 1",
    "apellido": "Hidalgo"
  },
  "fechaYHora": "2023-11-15T16:15:00"
}

###################ELIMINAR PACIENTE POR ID
DELETE http://localhost:8081/turnos/1 HTTP/1.1



